/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class create {
  public static int create_connect() {
    return createJNI.create_connect();
  }

  public static void create_disconnect() {
    createJNI.create_disconnect();
  }

  public static void set_create_mode(char mode) {
    createJNI.set_create_mode(mode);
  }

  public static void create_drive_direct(SWIGTYPE_p_int16_t left_speed, SWIGTYPE_p_int16_t right_speed) {
    createJNI.create_drive_direct(SWIGTYPE_p_int16_t.getCPtr(left_speed), SWIGTYPE_p_int16_t.getCPtr(right_speed));
  }

  public static void create_drive(SWIGTYPE_p_int16_t speed, SWIGTYPE_p_int16_t radius) {
    createJNI.create_drive(SWIGTYPE_p_int16_t.getCPtr(speed), SWIGTYPE_p_int16_t.getCPtr(radius));
  }

  public static void create_turn(SWIGTYPE_p_int16_t speed, SWIGTYPE_p_int16_t angle) {
    createJNI.create_turn(SWIGTYPE_p_int16_t.getCPtr(speed), SWIGTYPE_p_int16_t.getCPtr(angle));
  }

  public static void create_wait_angle(SWIGTYPE_p_int16_t angle) {
    createJNI.create_wait_angle(SWIGTYPE_p_int16_t.getCPtr(angle));
  }

  public static SWIGTYPE_p_uint8_t get_create_left_bump() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_left_bump(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_right_bump() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_right_bump(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_left_wheel_drop() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_left_wheel_drop(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_right_wheel_drop() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_right_wheel_drop(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_caster_wheel_drop() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_caster_wheel_drop(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_wall() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_wall(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_left_cliff() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_left_cliff(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_right_cliff() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_right_cliff(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_left_front_cliff() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_left_front_cliff(), true);
  }

  public static SWIGTYPE_p_uint8_t get_create_right_front_cliff() {
    return new SWIGTYPE_p_uint8_t(createJNI.get_create_right_front_cliff(), true);
  }

  public static SWIGTYPE_p_uint16_t get_create_left_cliff_analog() {
    return new SWIGTYPE_p_uint16_t(createJNI.get_create_left_cliff_analog(), true);
  }

  public static SWIGTYPE_p_uint16_t get_create_right_cliff_analog() {
    return new SWIGTYPE_p_uint16_t(createJNI.get_create_right_cliff_analog(), true);
  }

  public static SWIGTYPE_p_uint16_t get_create_left_front_cliff_analog() {
    return new SWIGTYPE_p_uint16_t(createJNI.get_create_left_front_cliff_analog(), true);
  }

  public static SWIGTYPE_p_uint16_t get_create_right_front_cliff_analog() {
    return new SWIGTYPE_p_uint16_t(createJNI.get_create_right_front_cliff_analog(), true);
  }

  public static SWIGTYPE_p_int16_t get_create_angle() {
    return new SWIGTYPE_p_int16_t(createJNI.get_create_angle(), true);
  }

}
