/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class createJNI {
  public final static native int create_connect();
  public final static native void create_disconnect();
  public final static native void set_create_mode(char jarg1);
  public final static native void create_drive_direct(long jarg1, long jarg2);
  public final static native void create_drive(long jarg1, long jarg2);
  public final static native void create_turn(long jarg1, long jarg2);
  public final static native void create_wait_angle(long jarg1);
  public final static native long get_create_left_bump();
  public final static native long get_create_right_bump();
  public final static native long get_create_left_wheel_drop();
  public final static native long get_create_right_wheel_drop();
  public final static native long get_create_caster_wheel_drop();
  public final static native long get_create_wall();
  public final static native long get_create_left_cliff();
  public final static native long get_create_right_cliff();
  public final static native long get_create_left_front_cliff();
  public final static native long get_create_right_front_cliff();
  public final static native long get_create_left_cliff_analog();
  public final static native long get_create_right_cliff_analog();
  public final static native long get_create_left_front_cliff_analog();
  public final static native long get_create_right_front_cliff_analog();
  public final static native long get_create_angle();
}
