#define IO_START 128
#define IO_BAUD 129
#define IO_SAFE 131
#define IO_FULL 132
#define IO_DEMO 136

#define IO_DRIVE 137
#define IO_DRIVE_DIRECT 145
#define IO_LEDS 139
#define IO_DIGITAL_OUTPUTS 147
#define IO_LOW_SIDE_DRIVERS 138
#define IO_SEND_IR 151

#define IO_SONG 140
#define IO_PLAY_SONG 141

#define IO_SENSORS 142
#define IO_QUERY_LIST 149

#define IO_STREAM 148
#define IO_PAUSE_RESUME_STREAM 150

#define IO_SCRIPT 152
#define IO_PLAY_SCRIPT 153
#define IO_SHOW_SCRIPT 154

#define IO_WAIT_TIME 155
#define IO_WAIT_DISTANCE 156
#define IO_WAIT_ANGLE 157
#define IO_WAIT_EVENT 156

#define IO_BUMPS_AND_WHEEL_DROPS 7
#define IO_WALL 8
#define IO_CLIFF_LEFT 9
#define IO_CLIFF_FRONT_LEFT 10
#define IO_CLIFF_FRONT_RIGHT 11
#define IO_CLIFF_RIGHT 12
#define IO_VIRTUAL_WALL 13
#define IO_LOW_SIDE_DRIVER_AND_WHEEL_OVERCURRENTS 14
#define IO_BUTTONS 18
#define IO_DISTANCE 19
#define IO_ANGLE 20
#define IO_CHARGING_STATE 21
#define IO_VOLTAGE 22
#define IO_CURRENT 23
#define IO_CARGO_BAY_DIGITAL_INPUTS 32

#define IO_WALL_SIGNAL 27
#define IO_CLIFF_LEFT_SIGNAL 28
#define IO_CLIFF_RIGHT_SIGNAL 31
#define IO_CLIFF_LEFT_FRONT_SIGNAL 29
#define IO_CLIFF_RIGHT_FRONT_SIGNAL 30
