/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class create implements createConstants {
  public static int create_connect() {
    return createJNI.create_connect();
  }

  public static void create_disconnect() {
    createJNI.create_disconnect();
  }

  public static void set_create_mode(char mode) {
    createJNI.set_create_mode(mode);
  }

  public static void create_drive_direct(short left_speed, short right_speed) {
    createJNI.create_drive_direct(left_speed, right_speed);
  }

  public static void create_drive(short speed, short radius) {
    createJNI.create_drive(speed, radius);
  }

  public static void create_turn(short speed, short angle) {
    createJNI.create_turn(speed, angle);
  }

  public static void create_wait_angle(short angle) {
    createJNI.create_wait_angle(angle);
  }

  public static short get_create_left_bump() {
    return createJNI.get_create_left_bump();
  }

  public static short get_create_right_bump() {
    return createJNI.get_create_right_bump();
  }

  public static short get_create_left_wheel_drop() {
    return createJNI.get_create_left_wheel_drop();
  }

  public static short get_create_right_wheel_drop() {
    return createJNI.get_create_right_wheel_drop();
  }

  public static short get_create_caster_wheel_drop() {
    return createJNI.get_create_caster_wheel_drop();
  }

  public static short get_create_wall() {
    return createJNI.get_create_wall();
  }

  public static short get_create_left_cliff() {
    return createJNI.get_create_left_cliff();
  }

  public static short get_create_right_cliff() {
    return createJNI.get_create_right_cliff();
  }

  public static short get_create_left_front_cliff() {
    return createJNI.get_create_left_front_cliff();
  }

  public static short get_create_right_front_cliff() {
    return createJNI.get_create_right_front_cliff();
  }

  public static int get_create_left_cliff_analog() {
    return createJNI.get_create_left_cliff_analog();
  }

  public static int get_create_right_cliff_analog() {
    return createJNI.get_create_right_cliff_analog();
  }

  public static int get_create_left_front_cliff_analog() {
    return createJNI.get_create_left_front_cliff_analog();
  }

  public static int get_create_right_front_cliff_analog() {
    return createJNI.get_create_right_front_cliff_analog();
  }

  public static short get_create_angle() {
    return createJNI.get_create_angle();
  }

}
