/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package at.afv.createlib;

public interface createConstants {
  public final static int CREATE_FULL_MODE = createJNI.CREATE_FULL_MODE_get();
  public final static int CREATE_SAVE_MODE = createJNI.CREATE_SAVE_MODE_get();
}
