package at.afv.createlib;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class createJNI {
  public final static native int CREATE_FULL_MODE_get();
  public final static native int CREATE_SAVE_MODE_get();
  public final static native int create_connect();
  public final static native void create_disconnect();
  public final static native void set_create_mode(char jarg1);
  public final static native void create_drive_direct(short jarg1, short jarg2);
  public final static native void create_drive(short jarg1, short jarg2);
  public final static native void create_turn(short jarg1, short jarg2);
  public final static native void create_wait_angle(short jarg1);
  public final static native short get_create_left_bump();
  public final static native short get_create_right_bump();
  public final static native short get_create_left_wheel_drop();
  public final static native short get_create_right_wheel_drop();
  public final static native short get_create_caster_wheel_drop();
  public final static native short get_create_wall();
  public final static native short get_create_left_cliff();
  public final static native short get_create_right_cliff();
  public final static native short get_create_left_front_cliff();
  public final static native short get_create_right_front_cliff();
  public final static native int get_create_left_cliff_analog();
  public final static native int get_create_right_cliff_analog();
  public final static native int get_create_left_front_cliff_analog();
  public final static native int get_create_right_front_cliff_analog();
  public final static native short get_create_angle();
}
